parties:
  - id: 1,
    name: Gjestelista
    logo: 'gjestelista.png'
  - id: 2,
    name: By og velferdslistaa
    logo: 'byogvel.svg'
  - id: 3,
    name: Liberal liste
    logo: 'liberalliste.svg'
  - id: 4,
    name: A-lista
    logo: 'alista.svg'
  - id: 5,
    name: Blå liste
    logo: 'blaliste.svg'
  - id: 6,
    name: Grønn liste
    logo: 'gronnliste.svg'
  - id: 7,
    name: Venstrealliansen
    logo: 'venstrealliansen.svg'
  - id: 8,
    name: Realistlista
    logo: 'Realistlista_logo_grnn.svg'

votes:
  - id: 1
    title: '7498: Større pikk til folket'
    href: '#'
    votes: 18
    totalVotes: 35
    for:
      - 1
      - 2
      - 3
      - 7
  - id: 2
    title: '2331: Ja til lavere studiestøtte så lenge regjeringen er rødgrønn'
    href: '#'
    votes: 15
    totalVotes: 32
    for:
      - 2
      - 4
      - 6
      - 7
      - 8
